sudo: required
language: node_js

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "ENCRYPTED_TOKEN"

branches:
  only:
    - main
    - /^release-[0-9]+\..*$/

stages:
  - build

jobs:
  include:
    - stage: build
      name: "Build the module"
      script:
        - npm run test
        - npm run lint
        - sonar-scanner --debug
